Update design for Create / Load NFT on DAO dashboard
HyphalDAO/TokenWalk pull request #15
Opened 2021-10-30 01:10 UTC by mudrila

Extract `CreateNFTModalContent` to reusable form, and actually use it in modal and on the DAO dashboard

2021-11-04 01:08 UTC, Koochr requested changes
The idea is correct, but:
1. Please remove "Create/Load NFT" modal from DAO collection page
2. Remove "success" stage from create NFT page and redirect user to "collection" instead
3. While doing p.3 make sure not to break success stage of create NFT modal (it is still used in user profile)
4. Also be sure that the new NFT appears on collection page after creation

2021-11-04 01:08 UTC, Koochr commented on src/pages/DAO/index.tsx
> +									domains={user?.myDomains as Domain[]}
instead of this insertion add a check that user is not nullish

2021-11-06 21:44 UTC, mudrila commented on src/components/DAO/DAOCollection/index.tsx
> -					<CreateNFTModal
After removing `CreateNFTModal` from this page - the component became fairly too small to keep it. Thus I just extracted `NFTGallery` to DAO Dashboard

2021-11-06 21:45 UTC, mudrila commented on src/pages/DAO/index.tsx
> -						<>
We don't this `Fragment` here anymore

2021-11-06 21:46 UTC, mudrila commented on src/pages/DAO/index.tsx
> +								afterCreate={() => push(`${pathname}?page=collection`)}
`afterCreate` is called right before setting the stage to "success", so it does the trick to not show success message and rather immediately redirect to collection

2021-11-12 01:14 UTC, merged